name: "units-test"
on:
  pull_request:
  push:
    branches:
      - v1

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    strategy:
      fail-fast: false
      matrix:
        host:
          [
            ubuntu-latest,
            macos-latest,
            windows-latest,
          ]
    runs-on: ${{matrix.host}}
    steps:
    - uses: actions/checkout@v2
    - uses: ./
    - run: zig version
    - run: zig build run
